<<<<<<< HEAD
CREATE TABLE `usuario` (
`nome` VARCHAR( 200 ) NOT NULL ,
`email` VARCHAR( 200 ) NOT NULL ,
`cpf` VARCHAR( 200 ) NOT NULL ,
`telefone` VARCHAR( 200 ) NOT NULL ,
`sexo` CHAR NOT NULL ,
`senha` VARCHAR( 200 ) NOT NULL ,
`dataNasc` DATE NOT NULL ,
`id` INT NOT NULL ,
PRIMARY KEY ( `id` )
)
=======
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
CREATE TABLE `quiz`.`usuario` ( `nome` VARCHAR NOT NULL , `email` VARCHAR NOT NULL , `cpf` VARCHAR NOT NULL , `telefone` VARCHAR NOT NULL , `sexo` CHAR NOT NULL , `senha` VARCHAR NOT NULL , `dataNasc` DATE NOT NULL , `id` INT NOT NULL , PRIMARY KEY (`id`)) ENGINE = InnoDB;
>>>>>>> update
